### ISSUE TITLE
Discussion: How to sum N loaders?

### ISSUE THREAD

**Issue by aurium** [nodejs/loaders-test#1]
I believe `pgp-loader` alone scarcely will be an use case. Cryptography makes sense if the data must be stored or traffic by insecure places. In a real case it could work together with `https-loader` or (pending)`imap-loader`. Like that, many use cases may need to sum loaders to achieve the desired feature.

I think "`--experimental-loader`" don't support an array of loaders, so what is the best path? Implement the support on Node.js or make a loader of loaders? _(I believe it must be a Node.js feature)_

Regardless of the chosen path, simply create a line of hooks (where the "defaultHook" parameter is the next loader hook) is enough? I think yes. We must to consider something?

**Comment by GeoffreyBooth** [comment]
Let's please discuss on https://github.com/nodejs/modules, I don't want people to need to start following this repo for discussion. I think the issues and PRs on this repo should be particular to the code in this repo.

**Comment by aurium** [comment]
Moved to https://github.com/nodejs/modules/issues/513
